### config/config.yaml

device: "cuda"

hydra:
    run:
        dir: "_results/${hydra.job.override_dirname}@${now:%Y-%m-%d_%H-%M-%S}"

dataset:
    name: "Synthetic"
    data_root: "data/nerf_dataset/"
    scene: "ficus"
    init_batch_size: 1024

scene:
    aabb: [-1.5, -1.5, -1.5, 1.5, 1.5, 1.5]
    near_plane: 2.0
    far_plane: 6.0

render:
    render_step_size: 0.005
    alpha_thre: 0.0
    cone_angle: 0.0

model:
    log2_hashmap_size: 17
    n_levels: 16
    n_neighbours: 16
    n_features_per_gauss: 10
    max_resolution: 1024
    num_splashes: 4
    fixed_std: False
    std_init_factor: 50
    std_final_factor: 5
    load_model_path: ""
    splits: [0.875, 0.9375]
    n_gausses: 40000

occupancy:
    grid_resolution: 128
    grid_nlvl: 1

optimizer:
    learning_rate: 1e-2
    gaussian_factor: 0.1
    weight_decay: 0.0
    eps: 1e-15

scheduler:
    milestones: [0.5, 0.75, 0.9]
    gamma: 0.33

trainer:
    max_steps: 1000
    log_every: 200
    save_every: 100
    visualize_every: 500
    size_decay_every: 100
    eval_only: False

    weight_surface: 1e-3
    weight_sigma: 1e-3
    weight_mip: 1e-3